<a href="https://colab.research.google.com/github/amandatz/computational-linear-algebra/blob/main/Atividade5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Atividade 5

Amanda Topanotti Zanette (22100776)

**Importações e funções auxiliares**

In [1]:
using LinearAlgebra
using Plots, Printf

function print_matrix(M, decimals::Int=4)
  for i in 1:size(M, 1)
    for j in 1:size(M, 2)
      @printf("%*.*f ", 10, decimals, M[i, j])
    end
    println()
  end
end

print_matrix (generic function with 2 methods)

Esse trecho de código é usado apenas para garantir a repetibilidade dos números aleatórios gerados.

In [2]:
using Random
Random.seed!(123)

TaskLocalRNG()

### Questão 1

Primeiro iremos gerar os 100 pontos aleatórios $x_i$ e construir $X$.

In [3]:
n = 100
X = rand(2, n)

2×100 Matrix{Float64}:
 0.9063    0.745673  0.253849  0.427328  …  0.31068   0.93875   0.0904866
 0.443494  0.512083  0.334152  0.867547     0.786312  0.918775  0.688171

Sabemos que
$$
\|x_i - x_j\|^2 = \|x_i\|^2 + \|x_j\|^2 - 2 x_i^\top x_j.
$$
Logo, pode-se construir a matriz $D$ da seguinte forma:

In [8]:
XT = transpose(X)
norms_squared = sum(XT.^2, dims=2)
D = norms_squared .+ norms_squared' .- 2 .* (XT * X)

100×100 Matrix{Float64}:
 0.0         0.0305053   0.437647     …   0.472287     0.226945    0.725418
 0.0305053   0.0         0.273551         0.26442      0.202677    0.460277
 0.437647    0.273551   -5.55112e-17      0.207679     0.810874    0.152017
 0.409235    0.227699    0.314606         0.0202057    0.264177    0.145638
 0.752772    0.567625    0.0675611        0.481706     1.33458     0.316912
 0.140048    0.143882    0.231205     …   0.567753     0.672656    0.666353
 0.77287     0.535286    0.0494429        0.267501     1.14491     0.1174
 0.266772    0.234221    0.848607         0.41394      0.00172399  0.778925
 0.0850472   0.108738    0.293332         0.578067     0.567661    0.721953
 0.457266    0.332279    0.0357187        0.404883     1.00259     0.332118
 0.00801747  0.0465803   0.40963      …   0.525866     0.320036    0.755981
 0.847497    0.560927    0.383323         0.0559683    0.651672    0.0656967
 0.760282    0.54512     0.0465427        0.356619     1.2304   

### Questão 2

Primeiro iremos construir a matriz $J = I - \frac{1}{n} e e^T$

In [7]:
I_n = Matrix{Float64}(I, n, n)
e = ones(n)
eeT = e * e'
J = I_n - (1/n) * eeT

100×100 Matrix{Float64}:
  0.99  -0.01  -0.01  -0.01  -0.01  …  -0.01  -0.01  -0.01  -0.01  -0.01
 -0.01   0.99  -0.01  -0.01  -0.01     -0.01  -0.01  -0.01  -0.01  -0.01
 -0.01  -0.01   0.99  -0.01  -0.01     -0.01  -0.01  -0.01  -0.01  -0.01
 -0.01  -0.01  -0.01   0.99  -0.01     -0.01  -0.01  -0.01  -0.01  -0.01
 -0.01  -0.01  -0.01  -0.01   0.99     -0.01  -0.01  -0.01  -0.01  -0.01
 -0.01  -0.01  -0.01  -0.01  -0.01  …  -0.01  -0.01  -0.01  -0.01  -0.01
 -0.01  -0.01  -0.01  -0.01  -0.01     -0.01  -0.01  -0.01  -0.01  -0.01
 -0.01  -0.01  -0.01  -0.01  -0.01     -0.01  -0.01  -0.01  -0.01  -0.01
 -0.01  -0.01  -0.01  -0.01  -0.01     -0.01  -0.01  -0.01  -0.01  -0.01
 -0.01  -0.01  -0.01  -0.01  -0.01     -0.01  -0.01  -0.01  -0.01  -0.01
 -0.01  -0.01  -0.01  -0.01  -0.01  …  -0.01  -0.01  -0.01  -0.01  -0.01
 -0.01  -0.01  -0.01  -0.01  -0.01     -0.01  -0.01  -0.01  -0.01  -0.01
 -0.01  -0.01  -0.01  -0.01  -0.01     -0.01  -0.01  -0.01  -0.01  -0.01
  ⋮                       

Agora, calculemos $G= -\frac{1}{2}JDJ$

In [10]:
G = -1/2 * J * D * J

100×100 Matrix{Float64}:
  0.161031    0.0933039  -0.0918391   …  -0.095179     0.146683   -0.17701
  0.0933039   0.056082   -0.0622653      -0.0437204    0.106342   -0.0969141
 -0.0918391  -0.0622653   0.0929381       0.00307828  -0.179328    0.0756439
 -0.0535051  -0.0152112  -0.0402368       0.120943     0.118148    0.102961
 -0.141319   -0.101219    0.16724        -0.0258523   -0.333098    0.101279
  0.0935896   0.0391981   0.0139649   …  -0.140329    -0.0735899  -0.144895
 -0.180853   -0.114535    0.146814        0.0517648   -0.267746    0.17155
  0.141009    0.10481    -0.183955        0.0473587    0.372658   -0.0903994
  0.123418    0.0590976  -0.014771       -0.143159    -0.0187648  -0.170367
 -0.0641474  -0.0541286   0.11258        -0.0580226   -0.237686    0.0230942
  0.161041    0.089285   -0.0738117   …  -0.11795      0.104156   -0.188273
 -0.175099   -0.0842878   0.022942        0.200599     0.0219387   0.240469
 -0.164911   -0.109804    0.157912        0.0168539   -0.3008

### Questão 3

### Questão 4