<a href="https://colab.research.google.com/github/amandatz/computational-linear-algebra/blob/main/Atividade1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Atividade Computacional 1

In [18]:
using LinearAlgebra
using Printf

function print_matrix(M)
    for i in 1:size(M, 1)
        for j in 1:size(M, 2)
            @printf("%10.4f ", M[i, j])
        end
        println()
    end
end

print_matrix (generic function with 1 method)

## Questão 1

In [2]:
function hilbert(n)
    return [1/(i + j - 1) for i in 1:n, j in 1:n]
end

hilbert (generic function with 1 method)

In [3]:
n_arr = [10, 100, 1000]
println("Número de condição para")
foreach(x -> println("n = $x : $(cond(hilbert(x)))"), n_arr)

Número de condição para
n = 10 : 1.602441698742836e13
n = 100 : 3.0310502811585376e19
n = 1000 : 3.956047868337803e21


## Questão 2

In [4]:
function solve_hilbert(n)
    A = hilbert(n)
    b = A[:, end]

    x = A \ b

    x_expected = zeros(n)
    x_expected[end] = 1

    error = norm(x - x_expected)

    println("Ordem n = $n")
    println("Erro ||x - x*|| = $error")
    println("Solução obtida x:\n", x, "\n")
end

solve_hilbert (generic function with 1 method)

In [5]:
n_arr = [10, 20, 40]
foreach(x -> solve_hilbert(x), n_arr)

Ordem n = 10
Erro ||x - x*|| = 8.82004958406119e-5
Solução obtida x:
[-1.4651366774146415e-10, 1.2775109034977263e-8, -2.7392949560830654e-7, 2.5030341548541955e-6, -1.1986975802570154e-5, 3.3058644240837314e-5, -5.4382884775336115e-5, 5.2670828788366856e-5, -2.7703346960148717e-5, 1.000006102109757]

Ordem n = 20
Erro ||x - x*|| = 17.479329722835804
Solução obtida x:
[6.354276716598471e-8, -1.1449407480753177e-5, 0.0005093624149355328, -0.00977814143573574, 0.10054654476794901, -0.615089576184316, 2.348349289209795, -5.600259111702343, 7.717335674775905, -3.9170834315471064, -4.588814509859795, 7.760472579842202, -1.133742642284071, -5.793760161860332, 5.946403306775728, -4.129904279845813, 3.8785846966303903, -2.9179764987116616, 1.1078592552977995, 0.8463590846746345]

Ordem n = 40
Erro ||x - x*|| = 18.75699831471733
Solução obtida x:
[-1.3113221114908623e-8, 2.7856066329896784e-6, -0.0001463101888717198, 0.0032971930296137567, -0.039325646913285425, 0.2737780116513607, -1.154979492

## Questão 3

In [6]:
A = [1.0 1.0; 1.0 1.0001]
b = [2.0, 2.0]
b_perturbed = [2.0, 2.0001]

kappa_A = cond(A, 2)

x = A \ b
x_perturbed = A \ b_perturbed

delta_x = x_perturbed - x

norm_delta_x = norm(delta_x, 2)
norm_x = norm(x, 2)
norm_delta_b = norm(b_perturbed - b, 2)
norm_b = norm(b, 2)

lhs = norm_delta_x / norm_x
rhs = kappa_A * (norm_delta_b / norm_b)

println("Número de condição κ2(A): ", kappa_A)
println("Solução x:\n", x)
println("Solução perturbada x_perturbed:\n", x_perturbed)
println("||δx|| / ||x|| = ", lhs)
println("κ2(A) * (||δb|| / ||b||) = ", rhs)
println("Desigualdade satisfeita? ", lhs ≤ rhs ? "Sim" : "Não")


Número de condição κ2(A): 40002.00007491187
Solução x:
[2.0, 0.0]
Solução perturbada x_perturbed:
[0.9999999999977796, 1.0000000000022204]
||δx|| / ||x|| = 0.7071067811881177
κ2(A) * (||δb|| / ||b||) = 1.4142842757027327
Desigualdade satisfeita? Sim


## Questão 4

In [7]:
function back_substitution(U, b)
    n = length(b)
    x = zeros(n)

    for i in n:-1:1
        sum_term = sum(U[i, j] * x[j] for j in i+1:n; init=0.0)
        x[i] = (b[i] - sum_term) / U[i, i]
    end

    return x
end

back_substitution (generic function with 1 method)

In [8]:
U = [2.0 -1.0 3.0; 0.0 1.0 4.0; 0.0 0.0 5.0]
b = [5.0, 6.0, 10.0]

x = back_substitution(U, b)

println("Solução x:\n", x)

Solução x:
[-1.5, -2.0, 2.0]


## Questão 5


In [31]:
function solve_system(n)
    B = rand(n, n)
    A = triu(B)

    b = A * ones(n)

    x = back_substitution(A, b)

    println("n = $n")
    println("A = ")
    print_matrix(A)
    println("b = ")
    print_matrix(b)
    println("x = ")
    print_matrix(x)
    println("================\n")
end


solve_system (generic function with 1 method)

In [32]:
n_arr = [2, 5, 10]
foreach(n -> solve_system(n), n_arr)

n = 2
A = 
    0.7107     0.7536 
    0.0000     0.5859 
b = 
    1.4642 
    0.5859 
x = 
    1.0000 
    1.0000 

n = 5
A = 
    0.9828     0.1108     0.1859     0.8171     0.3524 
    0.0000     0.4190     0.5216     0.5050     0.2362 
    0.0000     0.0000     0.1184     0.8661     0.8693 
    0.0000     0.0000     0.0000     0.7525     0.1596 
    0.0000     0.0000     0.0000     0.0000     0.1303 
b = 
    2.4490 
    1.6818 
    1.8538 
    0.9120 
    0.1303 
x = 
    1.0000 
    1.0000 
    1.0000 
    1.0000 
    1.0000 

n = 10
A = 
    0.4505     0.6376     0.9266     0.5148     0.8235     0.4426     0.8057     0.3847     0.2506     0.8588 
    0.0000     0.0382     0.4655     0.1928     0.4102     0.5448     0.0328     1.0000     0.1702     0.6541 
    0.0000     0.0000     0.5986     0.6462     0.4991     0.4543     0.6924     0.6817     0.5789     0.4419 
    0.0000     0.0000     0.0000     0.9187     0.1088     0.1859     0.5138     0.2681     0.7155     0.4216 
    0.